name: docs

on:
  push:
    branches: ["3.3.x"]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout           # 第一步，检出仓库副本
        uses: actions/checkout@v4
      - name: Yarn Setup         # 第二步，安装Yarn
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: '20.x'
      - name: 安装依赖 
        run: yarn install
      - name: Build              # 第三步，打包代码
        run: yarn docs:build
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages_threshold: major_outage
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      #- name: 部署到 GitHub Pages
      #  uses: crazy-max/ghaction-github-pages@v4
      #  with:
      #    # 部署到 gh-pages 分支
      #    target_branch: 3.3.x
      #    # 部署目录为 VuePress 的默认输出目录
      ##    build_dir: publish
      #  env:
      #    # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
